wget -qnc http://data.statmt.org/news-crawl/en/news.2007.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2008.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2009.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2010.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2011.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2012.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2013.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2014.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2015.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2016.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2017.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2018.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-crawl/en/news.2019.en.shuffled.deduped.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2011.en.filtered.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2012.en.filtered.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2013.en.filtered.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2014.en.filtered.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2015.en.filtered.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2016.en.filtered.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2017.en.filtered.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2018.en.filtered.gz &
wget -qnc http://data.statmt.org/news-discussions/en/news-discuss.2019.en.filtered.gz &
wget -qnc http://www.statmt.org/europarl/v9/training-monolingual/europarl-v9.cs.gz &
wget -qnc http://www.statmt.org/europarl/v9/training-monolingual/europarl-v9.de.gz &
wget -qnc http://www.statmt.org/europarl/v9/training-monolingual/europarl-v9.en.gz &
wget -qnc http://www.statmt.org/europarl/v9/training-monolingual/europarl-v9.es.gz &
wget -qnc http://www.statmt.org/europarl/v9/training-monolingual/europarl-v9.fi.gz &
wget -qnc http://www.statmt.org/europarl/v9/training-monolingual/europarl-v9.lt.gz &
wget -qnc http://www.statmt.org/europarl/v9/training-monolingual/europarl-v9.pl.gz &
wget -qnc http://www.statmt.org/europarl/v9/training-monolingual/europarl-v9.pt.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.ar.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.cs.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.de.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.en.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.es.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.fr.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.hi.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.id.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.it.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.ja.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.kk.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.nl.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.pt.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.ru.gz &
wget -qnc http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.zh.gz &

